version: 2.1

  orbs:
    checkmarx: justgiving/checkmarx@1.0.0
    whitesource: justgiving/whitesource@1.0.0

  workflows:
    version: 2
    security:
      jobs:
        - whitesource/scan:
            name: whitesource
            context: security-whitesource
            registry-url: 651244981378.dkr.ecr.eu-west-1.amazonaws.com
            config: agent.nodejs.config
            filters:
              branches:
                only: master
        - checkmarx/scan:
            name: checkmarx
            context: security-checkmarx
            registry-url: 651244981378.dkr.ecr.eu-west-1.amazonaws.com
            filters:
              branches:
                only: master
