version: 2.1

  orbs:
    checkmarx: justgiving/checkmarx@2.0.0

  workflows:
    version: 2
    security:
      jobs:
        - checkmarx/scan:
            name: checkmarx
            context: security-checkmarx
            filters:
              branches:
                only: master
